package net.blueskiez77.reach_display.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.awt.*;

public class ConfigGUI {
    public static Screen create (Screen parent) {
        DisplayConfig c = DisplayConfig.INSTANCE;

        return YetAnotherConfigLib.createBuilder()
                .title(Component.literal("Reach Display"))

                // ---------- GENERAL ---------- //

                .category(ConfigCategory.createBuilder()
                        .name(Component.literal("General"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.literal("Enabled"))
                                .description(OptionDescription.of(Component.literal("Enable/Disable the entire mod")))
                                .binding(true, () -> c.enabled, v -> c.enabled = v)
                                .controller(opt -> BooleanControllerBuilder.create(opt)
                                        .coloured(true))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.literal("Show Players Only"))
                                .description(OptionDescription.of(Component.literal("When enabled, your reach only activates for players. Attacks on mobs, animals, and other entities won't be tracked or shown or counted in your average.")))
                                .binding(true, () -> c.showPlayersOnly, v -> c.showPlayersOnly = v)
                                .controller(opt -> BooleanControllerBuilder.create(opt)
                                        .coloured(true))
                                .build())
                        .option(Option.<DisplayConfig.DistanceCalculationMethod>createBuilder()
                                .name(Component.literal("Distance Calculation Method"))
                                .description(OptionDescription.of(Component.literal("CLOSEST_POINT measures the distance from the player's eyes to the closest point on the target's hitbox. RAY_HIT_POINT measures the distance from the player's eyes to the point where your crosshair ray intersects the target's hitbox. NOTE: RAY_HIT_POINT can occasionally return -1 due to a uncommen edge case.")))
                                .binding(DisplayConfig.DistanceCalculationMethod.CLOSEST_POINT, () -> c.distanceCalculationMethod, v -> c.distanceCalculationMethod = v)
                                .controller(opt -> EnumControllerBuilder.create(opt)
                                        .enumClass(DisplayConfig.DistanceCalculationMethod.class))
                                .build())
                        .option(ButtonOption.createBuilder()
                                .name(Component.literal("Edit HUD Layout"))
                                .action((screen, opt) -> Minecraft.getInstance().setScreenAndShow(new HUDConfig(screen)))
                                .build())
                        .option(ButtonOption.createBuilder()
                                .name(Component.literal("Reset HUD Positions"))
                                .description(OptionDescription.of(Component.literal("This resets the position of the hit numbers (from top to bottom) distance, hit distance, and average hit distance. NOTE: You may need to use this option if you updated from an older version of the mod")))
                                .action((screen, opt) -> {
                                    DisplayConfig cfg = DisplayConfig.INSTANCE;
                                    cfg.distanceXOffset   = 0.5; cfg.distanceYOffset   = 0.55;
                                    cfg.hitXOffset        = 0.5; cfg.hitYOffset        = 0.65;
                                    cfg.averageHitXOffset = 0.5; cfg.averageHitYOffset = 0.9;
                                    ConfigManager.save();
                                })
                                .build())
                        .build())

                // ---------- DISTANCE ---------- //

                .category(ConfigCategory.createBuilder()
                        .name(Component.literal("Distance"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.literal("Enabled"))
                                .description(OptionDescription.of(Component.literal("Enable/Disable the distance number")))
                                .binding(true, () -> c.distanceEnabled, v -> c.distanceEnabled = v)
                                .controller(opt -> BooleanControllerBuilder.create(opt).coloured(true))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.literal("Scale"))
                                .description(OptionDescription.of(Component.literal("Size of the distance number")))
                                .binding(1.0f, () -> c.distanceTextScale, v -> c.distanceTextScale = v)
                                .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                        .range(0.1f, 4.0f)
                                        .step(0.1f))
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.literal("Text Color"))
                                .description(OptionDescription.of(Component.literal("Color of the distance number")))
                                .binding(new Color(0xFFFFFF), () -> new Color(c.distanceTextColor), v -> c.distanceTextColor = v.getRGB())
                                .controller(ColorControllerBuilder::create)
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.literal("Text Opacity"))
                                .description(OptionDescription.of(Component.literal("Opacity of the distance number")))
                                .binding(1.00, () -> c.distanceTextOpacity, v -> c.distanceTextOpacity = v)
                                .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                        .range(0.01, 1.00)
                                        .step(0.01))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.literal("Text Shadow"))
                                .description(OptionDescription.of(Component.literal("Enables/Disables the distance text shadow")))
                                .binding(false, () -> c.distanceTextShadow, v -> c.distanceTextShadow = v)
                                .controller(opt -> BooleanControllerBuilder.create(opt).coloured(true))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.literal("Decimal Places"))
                                .description(OptionDescription.of(Component.literal("Set the displayed precision of the distance number")))
                                .binding(2, () -> c.distanceDecimalPlaces, v -> c.distanceDecimalPlaces = v)
                                .controller(opt -> IntegerFieldControllerBuilder.create(opt)
                                        .range(1, 10))
                                .build())
                        .build())

                // ---------- HIT DISTANCE ---------- //

                .category(ConfigCategory.createBuilder()
                        .name(Component.literal("Hit Distance"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.literal("Enabled"))
                                .description(OptionDescription.of(Component.literal("Enable/Disable the hit distance number")))
                                .binding(true, () -> c.hitDistanceEnabled, v -> c.hitDistanceEnabled = v)
                                .controller(opt -> BooleanControllerBuilder.create(opt).coloured(true))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.literal("Scale"))
                                .description(OptionDescription.of(Component.literal("Size of the hit distance number")))
                                .binding(1.0f, () -> c.hitDistanceTextScale, v -> c.hitDistanceTextScale = v)
                                .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                        .range(0.1f, 4.0f)
                                        .step(0.1f))
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.literal("Text Color"))
                                .description(OptionDescription.of(Component.literal("Color of the hit distance number")))
                                .binding(new Color(0xFFFFFF), () -> new Color(c.hitDistanceTextColor), v -> c.hitDistanceTextColor = v.getRGB())
                                .controller(ColorControllerBuilder::create)
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.literal("Text Opacity"))
                                .description(OptionDescription.of(Component.literal("Opacity of the hit distance number")))
                                .binding(1.00, () -> c.hitDistanceTextOpacity, v -> c.hitDistanceTextOpacity = v)
                                .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                        .range(0.01, 1.00)
                                        .step(0.01))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.literal("Text Shadow"))
                                .description(OptionDescription.of(Component.literal("Enables/Disables the hit distance text shadow")))
                                .binding(false, () -> c.hitDistanceTextShadow, v -> c.hitDistanceTextShadow = v)
                                .controller(opt -> BooleanControllerBuilder.create(opt).coloured(true))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.literal("Hit Distance Decimal Places"))
                                .description(OptionDescription.of(Component.literal("Set the displayed precision of the hit distance number")))
                                .binding(2, () -> c.hitDistanceDecimalPlaces, v -> c.hitDistanceDecimalPlaces = v)
                                .controller(opt -> IntegerFieldControllerBuilder.create(opt)
                                        .range(1, 10))
                                .build())
                        .build())

                // ---------- AVERAGE HIT DISTANCE ---------- //

                .category(ConfigCategory.createBuilder()
                        .name(Component.literal("Average Hit Distance"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.literal("Enabled"))
                                .description(OptionDescription.of(Component.literal("Enable/Disable the average hit distance number")))
                                .binding(false, () -> c.averageHitEnabled, v -> c.averageHitEnabled = v)
                                .controller(opt -> BooleanControllerBuilder.create(opt).coloured(true))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.literal("Number of Hits Counted"))
                                .description(OptionDescription.of(Component.literal("The number of hits counted in the average")))
                                .binding(5, () -> c.numberOfHitsCounted, v -> c.numberOfHitsCounted = v)
                                .controller(opt -> IntegerFieldControllerBuilder.create(opt)
                                        .range(1, 1024))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.literal("Scale"))
                                .description(OptionDescription.of(Component.literal("Size of the average hit distance number")))
                                .binding(1.0f, () -> c.averageHitTextScale, v -> c.averageHitTextScale = v)
                                .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                        .range(0.1f, 4.0f)
                                        .step(0.1f))
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.literal("Text Color"))
                                .description(OptionDescription.of(Component.literal("Color of the average hit distance number")))
                                .binding(new Color(0xFFFFFF), () -> new Color(c.averageHitTextColor), v -> c.averageHitTextColor = v.getRGB())
                                .controller(ColorControllerBuilder::create)
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.literal("Text Opacity"))
                                .description(OptionDescription.of(Component.literal("Opacity of the average hit distance number")))
                                .binding(1.00, () -> c.averageHitTextOpacity, v -> c.averageHitTextOpacity = v)
                                .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                        .range(0.01, 1.00)
                                        .step(0.01))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.literal("Text Shadow"))
                                .description(OptionDescription.of(Component.literal("Enables/Disables the average hit distance text shadow")))
                                .binding(false, () -> c.averageHitTextShadow, v -> c.averageHitTextShadow = v)
                                .controller(opt -> BooleanControllerBuilder.create(opt).coloured(true))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.literal("Average Hit Distance Decimal Places"))
                                .description(OptionDescription.of(Component.literal("Set the displayed precision of the average hit distance number")))
                                .binding(2, () -> c.averageHitDecimalPlaces, v -> c.averageHitDecimalPlaces = v)
                                .controller(opt -> IntegerFieldControllerBuilder.create(opt)
                                        .range(1, 10))
                                .build())
                        .build())

                .save(ConfigManager::save)
                .build()
                .generateScreen(parent);
    }
}